#!/bin/sh

set -e

rm -rf .git/tags
mkdir -p .git/tags

# Generate for PHP Files
git ls-files \
	| ctags \
		--recurse \
		--tag-relative \
		--exclude=.git \
		--sort=yes \
		--append \
		--PHP-kinds=+cf \
		--languages=php \
		--regex-PHP='/abstract class ([^ ]*)/\1/c/' \
		--regex-PHP='/^interface ([^ ]*)/\1/c/' \
		--regex-PHP='/(public |static |abstract |protected |private )+function +([^ (]*)/\2/f/' \
		-f.git/php.tags

